name: CI Mutation Testing

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run:  |
            sudo apt-get update
            sudo apt-get upgrade -y
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 11
            sudo apt-get install -y cmake make libsqlite3-dev sqlite3 libclang-11-dev

    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake libboost-all-dev libfmt-dev libspdlog-dev

    - name: Install Mull
      run: |
          wget https://github.com/mull-project/mull/releases/download/0.21.0/Mull-12-0.21.0-LLVM-12.0-ubuntu-20.04.deb
          sudo dpkg -i Mull-12-0.21.0-LLVM-12.0-ubuntu-20.04.deb


    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build

    - name: Build CMake
      run: cmake --build ${{ github.workspace }}/build

    - name: Test
      run: cmake --build ${{ github.workspace }}/build --target test

    - name: Run Mull
      run: |
        mull-cxx --mutators=cxx_arithmetic,cxx_relational,cxx_logical,cxx_bitwise,cxx_assignment,cxx_unary,cxx_conditional,cxx_switch,cxx_remove_void,cxx_replace_call,cxx_remove_negation,cxx_add_void,cxx_add_mutations,cxx_add_random --reporters=IDE ${{ github.workspace }}/build/mutants.sqlite3 --compilers=clang --linker=clang

    - name: Generate Mutation Report
      run: |
          sudo apt-get install -y python3 python3-pip
          sudo pip3 install cxx_diff
          cxx_diff -reporter=HTML -mutant-db=${{ github.workspace }}/build/mutants.sqlite3 > ${{ github.workspace }}/build/mutation_report.html
