name: CI Mutation Testing

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run:  |
            sudo apt-get update
            sudo apt-get upgrade -y
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 11
            sudo apt-get install -y cmake make libsqlite3-dev sqlite3 libclang-11-dev

    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake libboost-all-dev libfmt-dev libspdlog-dev

    - name: Install Mull
      run: |
          wget https://github.com/mull-project/mull/releases/download/0.21.0/Mull-12-0.21.0-LLVM-12.0-ubuntu-20.04.deb
          sudo dpkg -i Mull-12-0.21.0-LLVM-12.0-ubuntu-20.04.deb


    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build

    - name: Build CMake
      run: cmake --build ${{ github.workspace }}/build

    - name: Test
      run: cmake --build ${{ github.workspace }}/build --target test

    - name: List contents of the .deb package
      run: |
        dpkg-deb --contents Mull-12-0.21.0-LLVM-12.0-ubuntu-20.04.deb


    - name: Mutation Testing
      run: |
          cd ${{ github.workspace }}/build
          mull-cxx -test-framework GoogleTest -mutators=all -output=mutants.sqlite3 ./test_return_one

    - name: Add mull-cxx to PATH
      run: echo "$MULL_CXX_PATH" >> $GITHUB_PATH

    - name: Mutation Testing
      run: |
          cd ${{ github.workspace }}/build
          mull-cxx -test-framework GoogleTest -mutators=all -output=mutants.sqlite3 ./test_return_one

    - name: Generate Mutation Report
      run: |
          sudo apt-get install -y python3 python3-pip
          sudo pip3 install cxx_diff
          cxx_diff -reporter=HTML -mutant-db=${{ github.workspace }}/build/mutants.sqlite3 > ${{ github.workspace }}/build/mutation_report.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/build
