name: CI Mutation Testing

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run:  |
            sudo apt-get update
            sudo apt-get upgrade -y
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 11
            sudo apt-get install -y cmake make libsqlite3-dev sqlite3 libclang-11-dev

    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake libboost-all-dev libfmt-dev libspdlog-dev

    - name: Install Mull
      run: |
          git clone https://github.com/mull-project/mull.git
          cd mull
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/llvm-11 -DLLVM_ROOT=/usr/lib/llvm-11 -DCMAKE_INSTALL_PREFIX=../install
          make -j
          sudo make install

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build

    - name: Build CMake
      run: cmake --build ${{ github.workspace }}/build

    - name: Test
      run: cmake --build ${{ github.workspace }}/build --target test

    - name: Mutation Testing
      run: |
          cd ${{ github.workspace }}/build
          ../mull/install/bin/mull-cxx -test-framework GoogleTest -mutators=all -output=mutants.sqlite3 ./test_return_one

    - name: Generate Mutation Report
      run: |
          sudo apt-get install -y python3 python3-pip
          sudo pip3 install cxx_diff
          cxx_diff -reporter=HTML -mutant-db=${{ github.workspace }}/build/mutants.sqlite3 > ${{ github.workspace }}/build/mutation_report.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/build
